### ISSUE TITLE
Issue to build on Swift/iOS9/XCode7.1.1

### ISSUE THREAD

**Issue by aguerere** [auth0/Lock-Twitter.iOS#4]
I am having an issue to build the module successfully for iOS 9 in XCode 7.1.1 with Swift.

Could not find any extra steps in the repo readme, and neither at the Cocoapod documentation.
The Podfile i am using is attached.
What do you suggest? Regards

![cannotbuildlocktwitter1](https://cloud.githubusercontent.com/assets/14084214/11316329/a817b34a-8fd5-11e5-8201-fe8a9b307513.png)
![cannotbuildlocktwitter2](https://cloud.githubusercontent.com/assets/14084214/11316331/cf0c5898-8fd5-11e5-9451-0cc2670f780b.png)
[Podfile.txt](https://github.com/auth0/Lock-Twitter.iOS/files/40731/Podfile.txt)

**Comment by smisiewicz** [comment]
I am seeing the same issue with the latest xCode Version 7.1 (7B91b). 
It fails to compile with "Could not build Objective-C module 'LockTwitter'" when importing with `import LockTwitter`

Any ideas?
